# Generated by Django 5.0.3 on 2024-04-12 20:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sem titulo', help_text='[Titulo do filme aqui]', max_length=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('sinopse', models.CharField(default='Sem sinopse', help_text='[Sinipse do filme aqui]', max_length=500, validators=[django.core.validators.MinValueValidator(10)])),
                ('genero', models.CharField(choices=[('Ação', 'Ação'), ('Adventura', 'Adventura'), ('Ficçao', 'Ficçao'), ('Horor', 'Horor'), ('Suspense', 'Suspense'), ('Guerra', 'Guerra'), ('Padrão', '')], default='Padrão', max_length=15)),
                ('clasificacao', models.CharField(default='padrao', max_length=10)),
                ('quantidade_avaliacoes', models.IntegerField(default=0, help_text='quantidade de avaliacoes', validators=[django.core.validators.MinValueValidator(0)])),
                ('nota', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(1)])),
                ('duracao', models.TimeField(default=datetime.time(0, 0))),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
