# Generated by Django 5.0.3 on 2024-04-15 23:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imdb',
            name='popularidade',
            field=models.IntegerField(default=0, help_text='quantidade de popularidade', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='imdb',
            name='sinopse',
            field=models.CharField(default='Sem sinopse', help_text='[Sinipse do filme aqui]', max_length=500, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='imdb',
            name='titulo',
            field=models.CharField(default='Sem titulo', help_text='[Titulo do filme aqui]', max_length=100, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
