# Generated by Django 5.0.3 on 2024-04-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0002_imdb_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='imdb',
            name='titulo',
            field=models.CharField(default='Sem titulo', max_length=100),
        ),
    ]
