# Generated by Django 5.0.3 on 2024-04-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0003_imdb_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='imdb',
            name='genero',
            field=models.CharField(choices=[('Ação', 'Ação'), ('Adventura', 'Adventura'), ('Ficçao', 'Ficçao'), ('Horor', 'Horor'), ('Suspense', 'Suspense'), ('Guerra', 'Guerra'), ('Padrão', 'Padrão')], default='Padrão', max_length=50),
        ),
        migrations.AddField(
            model_name='imdb',
            name='sinopse',
            field=models.CharField(default='Sem titulo', help_text='[Sinipse do filme aqui]', max_length=500),
        ),
        migrations.AlterField(
            model_name='imdb',
            name='titulo',
            field=models.CharField(default='Sem titulo', help_text='[Titulo do filme aqui]', max_length=100),
        ),
    ]
