# Generated by Django 5.0.3 on 2024-04-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0004_imdb_genero_imdb_sinopse_alter_imdb_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imdb',
            name='sinopse',
            field=models.CharField(default='Sem sinopse', help_text='[Sinipse do filme aqui]', max_length=500),
        ),
    ]
