# Generated by Django 5.0.3 on 2024-04-10 00:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0005_alter_imdb_sinopse'),
    ]

    operations = [
        migrations.AddField(
            model_name='imdb',
            name='clasificacao',
            field=models.CharField(max_length=10, default='Sem', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='imdb',
            name='duracao',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='imdb',
            name='nota',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='imdb',
            name='quantidade_avaliacoes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='imdb',
            name='genero',
            field=models.CharField(choices=[('Ação', 'Ação'), ('Adventura', 'Adventura'), ('Ficçao', 'Ficçao'), ('Horor', 'Horor'), ('Suspense', 'Suspense'), ('Guerra', 'Guerra'), ('Padrão', '')], default='Padrão', max_length=15),
        ),
        migrations.AlterField(
            model_name='imdb',
            name='sinopse',
            field=models.CharField(default='Sem sinopse', help_text='[Sinipse do filme aqui]', max_length=500, validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='imdb',
            name='titulo',
            field=models.CharField(default='Sem titulo', help_text='[Titulo do filme aqui]', max_length=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
