# Generated by Django 5.0.3 on 2024-04-10 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0006_imdb_clasificacao_imdb_duracao_imdb_nota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imdb',
            name='clasificacao',
            field=models.CharField(default='vazio', max_length=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
