# Generated by Django 5.0.3 on 2024-04-10 00:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0008_alter_imdb_clasificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imdb',
            name='clasificacao',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
