# Generated by Django 5.0.3 on 2024-04-10 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0009_alter_imdb_clasificacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imdb',
            name='clasificacao',
        ),
    ]
