# Generated by Django 5.0.3 on 2024-04-10 00:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0012_alter_imdb_clasificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imdb',
            name='quantidade_avaliacoes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
