# Generated by Django 5.0.3 on 2024-04-10 00:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0014_remove_imdb_clasificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='imdb',
            name='clasificacao',
            field=models.CharField(default='hghhjgfhg', max_length=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
