# Generated by Django 5.0.3 on 2024-04-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0015_imdb_clasificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imdb',
            name='clasificacao',
            field=models.CharField(default='hghhjgfhg', max_length=10),
        ),
    ]
