# Generated by Django 5.0.3 on 2024-04-10 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0016_alter_imdb_clasificacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imdb',
            name='clasificacao',
        ),
        migrations.RemoveField(
            model_name='imdb',
            name='duracao',
        ),
        migrations.RemoveField(
            model_name='imdb',
            name='nota',
        ),
        migrations.RemoveField(
            model_name='imdb',
            name='quantidade_avaliacoes',
        ),
    ]
