# Generated by Django 5.0.3 on 2024-04-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0017_remove_imdb_clasificacao_remove_imdb_duracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imdb',
            name='clasificacao',
            field=models.CharField(default='hhjgfhg', max_length=10),
        ),
    ]
