# Generated by Django 5.0.3 on 2024-04-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0018_imdb_clasificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imdb',
            name='clasificacao',
            field=models.CharField(default='padrao', max_length=10),
        ),
    ]
