# Generated by Django 5.0.3 on 2024-04-11 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0019_alter_imdb_clasificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='imdb',
            name='quantidade_avaliacoes',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
