# Generated by Django 5.0.3 on 2024-04-11 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0020_imdb_quantidade_avaliacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imdb',
            name='quantidade_avaliacoes',
            field=models.IntegerField(default=0, help_text='quantidade de avaliacoes', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
