# Generated by Django 5.0.3 on 2024-04-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='torcedores',
            field=models.IntegerField(default=0),
        ),
    ]
