# Generated by Django 5.0.3 on 2024-04-08 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0002_example_torcedores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='nome',
            field=models.CharField(help_text='Nome da pessoa', max_length=200),
        ),
        migrations.AlterField(
            model_name='example',
            name='torcedores',
            field=models.IntegerField(default=0, help_text='Número de tocedores', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
