# Generated by Django 5.0.3 on 2024-04-15 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0003_alter_example_nome_alter_example_torcedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da pessoa', max_length=100, verbose_name='Full name')),
                ('birth', models.DateField(help_text='Data de nascimento', verbose_name='Birth date')),
                ('cpf', models.CharField(help_text='CPF da pessoa', max_length=100, verbose_name='CPF number')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Passaport',
            fields=[
                ('number', models.CharField(help_text='Número do passaporte', max_length=100, verbose_name='Passaport number')),
                ('inssue_date', models.DateField(help_text='Data de emissão', verbose_name='Inssue date')),
                ('expiration_date', models.DateField(help_text='Data de expiração', verbose_name='Expiration date')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='exemplo.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
